-- This file is intentionally left blank to resolve a migration history issue.
-- A previously generated migration (0004) was deleted, but drizzle-kit still
-- looks for it in the sequence. This empty file satisfies the check and allows
-- subsequent migrations to run correctly. 